### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by GANHONG1995** [flyqieqq/WhmcsPortForward#1]
已解决

**Comment by GANHONG1995** [comment]
PHP Fatal error:  Class 'Workerman\Worker' not found in /root/pfnode/start_autoload.php on line 6

Fatal error: Class 'Workerman\Worker' not found in /root/pfnode/start_autoload.php on line 6
[root@iZrj91o5954faci2prsqyeZ pfnode]# php start.php start Daemon: php start.php start -d
PHP Parse error:  syntax error, unexpected '@' in /root/pfnode/start_autoload.php on line 42

Parse error: syntax error, unexpected '@' in /root/pfnode/start_autoload.php on line 42
[root@iZrj91o5954faci2prsqyeZ pfnode]# php start.php start Daemon: php start.php start -d
PHP Warning:  require_once(/root/pfnode/vendor/autoload.php): failed to open stream: No such file or directory in /root/pfnode/start.php on line 18

Warning: require_once(/root/pfnode/vendor/autoload.php): failed to open stream: No such file or directory in /root/pfnode/start.php on line 18
PHP Fatal error:  require_once(): Failed opening required '/root/pfnode/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /root/pfnode/start.php on line 18

Fatal error: require_once(): Failed opening required '/root/pfnode/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /root/pfnode/start.php on line 18

**Comment by GANHONG1995** [comment]
PHP Fatal error:  Class 'Workerman\Worker' not found in /root/pfnode/start_autoload.php on line 6

Fatal error: Class 'Workerman\Worker' not found in /root/pfnode/start_autoload.php on line 6
[root@pfnode]# php start.php start Daemon: php start.php start -d
PHP Parse error:  syntax error, unexpected '@' in /root/pfnode/start_autoload.php on line 42

Parse error: syntax error, unexpected '@' in /root/pfnode/start_autoload.php on line 42
[root@pfnode]# php start.php start Daemon: php start.php start -d
PHP Warning:  require_once(/root/pfnode/vendor/autoload.php): failed to open stream: No such file or directory in /root/pfnode/start.php on line 18

Warning: require_once(/root/pfnode/vendor/autoload.php): failed to open stream: No such file or directory in /root/pfnode/start.php on line 18
PHP Fatal error:  require_once(): Failed opening required '/root/pfnode/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /root/pfnode/start.php on line 18

Fatal error: require_once(): Failed opening required '/root/pfnode/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /root/pfnode/start.php on line 18

**Comment by flyqieqq** [comment]
感谢支持，已解决就先关闭这个issue了哈~
